-- One admin user, named admin1 with passwor 4dm1n and authority admin
INSERT INTO users(username,password,enabled) VALUES ('admin1','4dm1n',TRUE);
INSERT INTO authorities VALUES ('admin1','admin');
-- One owner user, named owner1 with passwor 0wn3r
INSERT INTO users(username,password,enabled) VALUES ('owner1','0wn3r',TRUE);
INSERT INTO authorities VALUES ('owner1','owner');
-- One vet user, named vet1 with passwor v3t
INSERT INTO users(username,password,enabled) VALUES ('vet1','v3t',TRUE);
INSERT INTO authorities VALUES ('vet1','veterinarian');


--INSERT INTO vets VALUES (1, 'James', 'Carter');
--INSERT INTO vets VALUES (2, 'Helen', 'Leary');
--INSERT INTO vets VALUES (3, 'Linda', 'Douglas');
--INSERT INTO vets VALUES (4, 'Rafael', 'Ortega');
--INSERT INTO vets VALUES (5, 'Henry', 'Stevens');
--INSERT INTO vets VALUES (6, 'Sharon', 'Jenkins');


--INSERT INTO specialties VALUES (1, 'radiology');
--INSERT INTO specialties VALUES (2, 'surgery');
--INSERT INTO specialties VALUES (3, 'dentistry');


--INSERT INTO vet_specialties VALUES (2, 1);
--INSERT INTO vet_specialties VALUES (3, 2);
--INSERT INTO vet_specialties VALUES (3, 3);
--INSERT INTO vet_specialties VALUES (4, 2);
--INSERT INTO vet_specialties VALUES (5, 1);


INSERT INTO types VALUES (1, 'cat');
INSERT INTO types VALUES (2, 'dog');
INSERT INTO types VALUES (3, 'lizard');
INSERT INTO types VALUES (4, 'snake');
INSERT INTO types VALUES (5, 'bird');
INSERT INTO types VALUES (6, 'hamster');
    
--INSERT INTO owners VALUES (id, firstName, LastName, telephone, address, username);
INSERT INTO owners VALUES (1, '12345678Z', 'George', 'Franklin', '6085551023', '110 W. Liberty St., Madison', 'owner1');
INSERT INTO owners VALUES (2, '52365678Y', 'Betty', 'Davis', '6085551749', '638 Cardinal Ave., Sun Prairie', 'admin1');
INSERT INTO owners VALUES (3, '52362222A', 'Eduardo', 'Rodriquez', '6085558763', '2693 Commerce St., McFarland', 'owner1');
--INSERT INTO owners VALUES (4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198', 'owner1');
--INSERT INTO owners VALUES (5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765', 'owner1');
--INSERT INTO owners VALUES (6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654', 'owner1');
--INSERT INTO owners VALUES (7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387', 'owner1');
--INSERT INTO owners VALUES (8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683', 'owner1');
--INSERT INTO owners VALUES (9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435', 'owner1');
--INSERT INTO owners VALUES (10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487', 'owner1');

--INSERT INTO pets VALUES (id, name, birth_date, owner_id, type_id)
INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (1, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (2, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (3, 'Rosy', '2011-04-17', 2, 3);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (4, 'Jewel', '2010-03-07', 2, 3);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (5, 'Iggy', '2010-11-30', 3, 4);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (6, 'George', '2010-01-20', 4, 5);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (7, 'Samantha', '2012-09-04', 1, 6);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (8, 'Max', '2012-09-04', 1, 6);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (9, 'Lucky', '2011-08-06', 5, 7);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (10, 'Mulligan', '2007-02-24', 2, 8);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (11, 'Freddy', '2010-03-09', 5, 9);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (12, 'Lucky', '2010-06-24', 2, 10);
--INSERT INTO pets(id,name,birth_date,type_id,owner_id) VALUES (13, 'Sly', '2012-06-08', 1, 10);

--INSERT INTO requests(id, date_req, employee_id, owner_id);
INSERT INTO requests(id, date_req) VALUES (1, '2030-08-01');
INSERT INTO requests(id, date_req) VALUES (2, '2031-08-01');
INSERT INTO requests(id, date_req) VALUES (3, '2032-08-01');

--INSERT INTO services(id, address, close, max, open, price, reception, room, request_id);
INSERT INTO services VALUES (1, 'New Address', '2012-06-08 10:10:10', 10, '2022-06-08 12:00', 2.5, 3, 'A1-23', 1);
INSERT INTO services VALUES (2, 'New Address 2', '2112-06-08 13:16', 4, '2015-06-08 10:15', 5.5, 3, 'C1-23', 1);
INSERT INTO services VALUES (3, 'Hello 2', '2212-06-08 13:10', 5, '2052-06-08 16:10', 3, 2, 'B1-23', 2);

 create table employees (
       id integer generated by default as identity,
        first_name varchar(255),
        last_name varchar(255),
        telephone varchar(255),
        dni varchar(255),
        username varchar(255),
        service_id integer,
        primary key (id)
    )

--INSERT INTO employees(id, first_name, last_name, telephone, dni, username, service_id);
INSERT INTO employees VALUES (1, 'Jeorge', 'Frank', '6115551023', '87654321A', 'vet1', 1);
INSERT INTO employees VALUES (2, 'Hoes', 'Mad', '6115551023', '87654721A', 'vet1', 2);
INSERT INTO employees VALUES (3, 'No Hoes', 'Mad', '6145556023', '87654341A', 'vet1', 3);

--INSERT INTO payments(id, credit_card, pay, date_pay, owner_id, service_id);
INSERT INTO payments VALUES (1, '1234 1234 1234 1234', 0.5, '2012-06-08', 1, 1);
INSERT INTO payments VALUES (2, '4234 1234 1234 5234', 1, '2012-06-08', 1, 1);
INSERT INTO payments VALUES (3, '3234 1234 1234 6234', 2, '2012-06-08', 1, 2);

UPDATE requests SET employee_id = 1  WHERE (id = 1); UPDATE requests SET owner_id = 1  WHERE (id = 1);
UPDATE requests SET employee_id = 2  WHERE (id = 2); UPDATE requests SET owner_id = 1  WHERE (id = 2);
UPDATE requests SET employee_id = 2  WHERE (id = 3); UPDATE requests SET owner_id = 3  WHERE (id = 3);

--INSERT INTO visits(id,pet_id,visit_date,description) VALUES (1, 7, '2013-01-01', 'rabies shot');
--INSERT INTO visits(id,pet_id,visit_date,description) VALUES (2, 8, '2013-01-02', 'rabies shot');
--INSERT INTO visits(id,pet_id,visit_date,description) VALUES (3, 8, '2013-01-03', 'neutered');
--INSERT INTO visits(id,pet_id,visit_date,description) VALUES (4, 7, '2013-01-04', 'spayed');

/*
  
    create table authorities (
       username varchar(255) not null,
        authority varchar(255),
        primary key (username)
    )
Hibernate: 
    
    create table base_clinic (
       dtype varchar(31) not null,
        id integer generated by default as identity,
        address varchar(255),
        close timestamp,
        open timestamp,
        rating integer not null check (rating>=0 AND rating<=5),
        description varchar(2024),
        max integer check (max<=9223372036854775807 AND max>=1),
        price double check (price<=9223372036854775807 AND price>=0),
        days integer check (days<=9223372036854775807 AND days>=1),
        request_id integer,
        type_id integer not null,
        services_id integer,
        primary key (id)
    )
Hibernate: 
    
    create table base_clinic_employees (
       base_clinic_id integer not null,
        employees_id integer not null,
        primary key (base_clinic_id, employees_id)
    )
Hibernate: 
    
    create table base_clinic_items (
       shop_id integer not null,
        items_id integer not null,
        primary key (shop_id, items_id)
    )
Hibernate: 
    
    create table clinic_types (
       id integer generated by default as identity,
        name varchar(50),
        primary key (id)
    )
Hibernate: 
    
    create table items (
       id integer generated by default as identity,
        description varchar(1024),
        price double not null check (price<=9223372036854775807 AND price>=0),
        sale double not null check (sale<=1 AND sale>=0),
        stock integer not null check (stock<=9223372036854775807 AND stock>=0),
        shop_id integer,
        primary key (id)
    )

Hibernate: 
    
    create table payments (
       id integer generated by default as identity,
        credit_card integer not null,
        pay double not null check (pay<=9223372036854775807 AND pay>=0),
        date_pay date,
        owner_id integer,
        service_id integer,
        primary key (id)
    )
Hibernate: 
    
    create table requests (
       id integer generated by default as identity,
        date date,
        owner_id integer,
        primary key (id)
    )*/